openapi: 3.2.0
info:
  title: London Stock Exchange Group LSEG World-Check One Upcoming…
  description: The World-Check One API enables developers to integrate the next generation of LSEG screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence.
  version: 2.61.0
  termsOfService: https://www.lseg.com/en/risk-intelligence/screening-solutions/world-check-kyc-screening/one-kyc-verification
  contact:
    name: LSEG World-Check One API Q&A
    url: https://community.developers.refinitiv.com/index.html
    email: c3r.api1@lseg.com
  license:
    name: Commercial
    url: https://www.lseg.com/en/risk-intelligence/screening-solutions/world-check-kyc-screening/one-kyc-verification
servers:
- url: https://api-worldcheck.refinitiv.com/v2
tags:
- name: Upcoming
  description: 'Operations for upcoming features and changes.


    **Note:** Requests to these endpoints will return an HTTP ''404 Not Found'' response status code until officially released.'
paths:
  /reports/status:
    get:
      operationId: getPaginatedMultipleReportStatus
      tags:
      - Upcoming
      summary: London Stock Exchange Group Get the report status for all active reports by…
      description: Get the report status for all active reports by pagination params.
      parameters:
      - name: Authorization
        description: The authorization credentials including 'keyId', 'algorithm', 'headers', 'signature' (see 'Security and Authentication details' documentation section for more details).
        in: header
        required: true
        schema:
          type: string
      - name: Date
        description: The date and time at which the message was originated in 'RFC 1123' format.
        in: header
        required: true
        schema:
          type: string
      - name: currentPage
        description: Current page number.
        in: query
        required: true
        schema:
          type: integer
          format: int32
          default: 1
      - name: itemsPerPage
        description: Report items per page.
        in: query
        required: true
        schema:
          type: integer
          format: int32
          enum:
          - 5
          - 15
          - 20
          default: 15
      responses:
        200:
          description: Report status of all active reports by pagination params.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedReportStatusesResponse'
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/PaginatedReportStatusesResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/CannotReturnResponse'
        415:
          $ref: '#/components/responses/UnsupportedMediaType'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500:
          $ref: '#/components/responses/UnexpectedError'
  /reports/{reportId}/error:
    get:
      operationId: getReportErrorDetails
      tags:
      - Upcoming
      summary: London Stock Exchange Group Get the error details for the given 'reportId'
      description: Get the error details for the given 'reportId'.
      parameters:
      - name: Authorization
        description: The authorization credentials including 'keyId', 'algorithm', 'headers', 'signature' (see 'Security and Authentication details' documentation section for more details).
        in: header
        required: true
        schema:
          type: string
      - name: Date
        description: The date and time at which the message was originated in 'RFC 1123' format.
        in: header
        required: true
        schema:
          type: string
      - name: reportId
        description: Report ID for which the status needs to be fetched.
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Error details for the given report ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportErrorResponse'
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ReportErrorResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/CannotReturnResponse'
        415:
          $ref: '#/components/responses/UnsupportedMediaType'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500:
          $ref: '#/components/responses/UnexpectedError'
  /reports/{reportId}:
    delete:
      operationId: cancelReportByReportId
      tags:
      - Upcoming
      summary: London Stock Exchange Group Cancel the report request for the given report ID
      description: Cancel the report request for the given report ID.
      parameters:
      - name: Authorization
        description: The authorization credentials including 'keyId', 'algorithm', 'headers', 'signature' (see 'Security and Authentication details' documentation section for more details).
        in: header
        required: true
        schema:
          type: string
      - name: Date
        description: The date and time at which the message was originated in 'RFC 1123' format.
        in: header
        required: true
        schema:
          type: string
      - name: reportId
        description: ID of the report to be cancelled.
        in: path
        required: true
        schema:
          type: string
      responses:
        204:
          description: The report cancelation status for the given report ID.
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/CannotReturnResponse'
        415:
          $ref: '#/components/responses/UnsupportedMediaType'
        429:
          $ref: '#/components/responses/TooManyRequests'
        500:
          $ref: '#/components/responses/UnexpectedError'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Error'
        application/octet-stream:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Error'
    CannotReturnResponse:
      description: Cannot return response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Error'
        application/octet-stream:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Error'
    TooManyRequests:
      description: The API client is making too many concurrent requests, and some are being throttled. Throttled requests can be retried (with an updated request Date and HTTP signature) after a short delay.
    Unauthorized:
      description: The request has failed an authorisation check. This can happen for a variety of reasons, such as an invalid or expired API key, an invalid HMAC signature or a request timing issue/problem with the Date header value. The API client should ensure a correctly synchronised clock is used to generate request timestamps.
    UnexpectedError:
      description: Unexpected error
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Error'
        application/octet-stream:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Error'
    UnsupportedMediaType:
      description: For requests with payloads, an unsupported Content-Type was specified. The World-Check One API only supports a content type of application/json.
  schemas:
    PaginationDetails:
      type: object
      required:
      - currentPage
      - itemsPerPage
      - totalItems
      properties:
        currentPage:
          type: integer
          description: Represents the current page number of the case dossier report.
          format: int32
        itemsPerPage:
          type: integer
          description: Represents the items per page in case dossier report.
          format: int32
        totalItems:
          type: integer
          description: Represents the total item count in case dossier report.
          format: int64
    ReportProgressStatus:
      type: string
      description: 'The real-time progress status of report during download.


        - COMPLETED - Report is successfully generated.

        - IN_PROGRESS - Report generation is in progress.

        - FAILED - Report failed to generate. Contact helpdesk for more details.

        - WAITING - Report is waiting in queue and yet to be processed.

        - UNKNOWN - Report status is unknown. Contact helpdesk for more details.

        - CANCELLED - Report request has been cancelled.

        '
      enum:
      - COMPLETED
      - IN_PROGRESS
      - FAILED
      - WAITING
      - UNKNOWN
      - CANCELLED
    ReportError:
      type: object
      required:
      - objectId
      - objectType
      - errorDescription
      properties:
        objectId:
          type: string
          description: Id of the object which has failed to process.
        objectType:
          type: string
          description: The type of the object that failed to process.
        errorDescription:
          type: string
          description: The details about the error.
    PaginatedReportStatusesResponse:
      type: object
      required:
      - paginationDetails
      - reports
      properties:
        paginationDetails:
          $ref: '#/components/schemas/PaginationDetails'
        reports:
          type: array
          items:
            $ref: '#/components/schemas/ReportStatus'
      example:
        paginationDetails:
          currentPage: 1
          itemsPerPage: 1
          totalItems: 1
        reports:
        - reportId: Report ID
          reportName: Report Name
          progressStatus: COMPLETED
          reportType: CASE_DOSSIER
          startDate: 2019-08-28 10:05:15+00:00
          completionDate: null
          deletionDate: null
          summary:
            processedCount: 13.0
            progressPercentage: 50.0
    Error:
      type: object
      required:
      - error
      - cause
      properties:
        error:
          type: string
        cause:
          type: string
        objectId:
          type: string
    ReportSummary:
      type: object
      required:
      - processedCount
      - progressPercentage
      properties:
        processedCount:
          type: integer
          description: Represents number of records processed.
          format: int32
        progressPercentage:
          type: integer
          description: Represents progress percentage of records processed.
          format: int32
    ReportType:
      type: string
      description: The type of report.
      enum:
      - CASE_DOSSIER
    ReportStatus:
      type: object
      required:
      - reportId
      - reportName
      - progressStatus
      - reportType
      properties:
        reportId:
          type: string
          description: Report ID for which the data needs to be fetched.
        reportName:
          type: string
          description: Name for the report. If not provided, system will generate the name for the report based on the type of report.
        progressStatus:
          description: Represents the status of the report for the specified 'reportId'.
          $ref: '#/components/schemas/ReportProgressStatus'
        reportType:
          description: The report type specifies the type of the report, like case dossier, case summary etc.
          $ref: '#/components/schemas/ReportType'
        startDate:
          type: string
          description: Represents the start date of the report.
          format: date-time
        completionDate:
          type: string
          description: Represents the completion date of the report.
          format: date-time
        deletionDate:
          type: string
          description: Represents the deletion date of the report.
          format: date-time
        summary:
          description: Summary of the report.
          $ref: '#/components/schemas/ReportSummary'
      example:
        reportId: Report ID
        reportName: Report Name
        progressStatus: COMPLETED
        reportType: CASE_DOSSIER
        startDate: 2019-08-28 10:05:15+00:00
        completionDate: null
        deletionDate: null
        summary:
          processedCount: 13.0
          progressPercentage: 50.0
    ReportErrorResponse:
      type: object
      required:
      - errorDetails
      properties:
        errorDetails:
          type: array
          items:
            $ref: '#/components/schemas/ReportError'
      example:
        errorDetails:
        - objectId: Error ID
          objectType: Error Type
          errorDescription: Error Description
externalDocs:
  description: Refer to the LSEG Developer Portal for additional documentation on the World-Check One API.
  url: https://developers.lseg.com/en/api-catalog/customer-and-third-party-screening/world-check-one-api
x-tagGroups:
- name: Upcoming Features and Changes
  tags:
  - upcoming
- name: Zero Footprint Screening
  tags:
  - zfs
- name: Case Management and Audit
  tags:
  - api-info
  - reference
  - group
  - case
  - audit
  - media-check
  - client-watchlist
  - user
  - passport-check
  - linked-cases
  - case-rating
  - smart-filter
  - reporting
